// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package msg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Body struct {
	_tab flatbuffers.Struct
}

func (rcv *Body) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Body) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Body) Val() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Body) MutateVal(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateBody(builder *flatbuffers.Builder, val uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependUint32(val)
	return builder.Offset()
}
