// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package msg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientLogin struct {
	_tab flatbuffers.Table
}

func GetRootAsClientLogin(buf []byte, offset flatbuffers.UOffsetT) *ClientLogin {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientLogin{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsClientLogin(buf []byte, offset flatbuffers.UOffsetT) *ClientLogin {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientLogin{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ClientLogin) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientLogin) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientLogin) UserId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientLogin) MutateUserId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func ClientLoginStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ClientLoginAddUserId(builder *flatbuffers.Builder, userId uint64) {
	builder.PrependUint64Slot(0, userId, 0)
}
func ClientLoginEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
