// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package msg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientLogout struct {
	_tab flatbuffers.Table
}

func GetRootAsClientLogout(buf []byte, offset flatbuffers.UOffsetT) *ClientLogout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientLogout{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsClientLogout(buf []byte, offset flatbuffers.UOffsetT) *ClientLogout {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientLogout{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ClientLogout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientLogout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientLogout) UserId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientLogout) MutateUserId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func ClientLogoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ClientLogoutAddUserId(builder *flatbuffers.Builder, userId uint64) {
	builder.PrependUint64Slot(0, userId, 0)
}
func ClientLogoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
