// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package msg

import "strconv"

type Payload byte

const (
	PayloadNONE            Payload = 0
	PayloadWorldUpdate     Payload = 1
	PayloadClientLogin     Payload = 2
	PayloadClientLoginResp Payload = 3
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:            "NONE",
	PayloadWorldUpdate:     "WorldUpdate",
	PayloadClientLogin:     "ClientLogin",
	PayloadClientLoginResp: "ClientLoginResp",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":            PayloadNONE,
	"WorldUpdate":     PayloadWorldUpdate,
	"ClientLogin":     PayloadClientLogin,
	"ClientLoginResp": PayloadClientLoginResp,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
